#!/usr/bin/env python3
"""Download a fixed, seeded subset of Argoverse 2 Motion Forecasting VAL scenarios.

Downloads exactly N_SCENARIOS scenario folders from the publicly readable S3
bucket using s5cmd with --no-sign-request. Only the chosen scenario folders are
copied; the rest of the split is never downloaded. The chosen IDs are recorded
in scenarios/manifest.txt so the subset is reproducible.

Layout:
  scenarios/av2_raw/val/<scenario_id>/scenario_<scenario_id>.parquet

Requires s5cmd on PATH: https://github.com/peak/s5cmd
"""

from __future__ import annotations

import argparse
import random
import re
import shutil
import subprocess
import sys
from pathlib import Path

S3_ROOT = "s3://argoverse/datasets/av2/motion-forecasting/val/"
S5CMD = "s5cmd"
SEED = 20240901
N_SCENARIOS = 2000
HEX32 = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")

ROOT = Path(__file__).resolve().parent
RAW_DIR = ROOT / "av2_raw" / "val"
MANIFEST = ROOT / "manifest.txt"


def run(cmd: list[str]) -> str:
    proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        print(proc.stderr, file=sys.stderr)
        raise RuntimeError(f"command failed: {' '.join(cmd)}")
    return proc.stdout


def list_scenario_dirs() -> list[str]:
    out = run([S5CMD, "--no-sign-request", "ls", S3_ROOT])
    dirs = []
    for line in out.splitlines():
        parts = line.split()
        if not parts:
            continue
        name = parts[-1].rstrip("/")
        if HEX32.fullmatch(name):
            dirs.append(name)
    if not dirs:
        raise RuntimeError(f"no scenario folders found under {S3_ROOT}; check s5cmd output format")
    return dirs


def select_subset(all_dirs: list[str], seed: int, n: int) -> list[str]:
    rng = random.Random(seed)
    return sorted(rng.sample(sorted(all_dirs), n))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n", type=int, default=N_SCENARIOS, help="number of scenarios to fetch")
    parser.add_argument("--seed", type=int, default=SEED, help="fixed seed for the subset")
    parser.add_argument("--numworkers", type=int, default=64, help="s5cmd concurrency")
    parser.add_argument("--dry-run", action="store_true", help="list and select ids without downloading")
    args = parser.parse_args()

    if shutil.which(S5CMD) is None:
        sys.exit(f"{S5CMD} not found on PATH; install from https://github.com/peak/s5cmd")

    all_dirs = list_scenario_dirs()
    chosen = select_subset(all_dirs, args.seed, args.n)
    print(f"bucket has {len(all_dirs)} scenario folders; selected {len(chosen)} (seed={args.seed})")

    manifest_text = (
        "# Argoverse 2 Motion Forecasting VAL scenario subset manifest\n"
        f"# Generated by scenarios/fetch_av2.py (seed={args.seed}, n={args.n}). One scenario id per line.\n"
        "# The committed list makes the subset reproducible; regenerate to verify.\n"
        + "\n".join(chosen)
        + "\n"
    )
    MANIFEST.write_text(manifest_text)
    print(f"wrote manifest: {MANIFEST}")

    if args.dry_run:
        return

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    batch = ROOT / "av2_raw" / "fetch_batch.txt"
    with open(batch, "w") as f:
        for sid in chosen:
            dest = RAW_DIR / sid
            dest.mkdir(parents=True, exist_ok=True)
            f.write(f'cp "{S3_ROOT}{sid}/*" "{dest}/"\n')
    print(f"downloading {len(chosen)} scenario folders (this can take a while)...")
    for attempt in range(1, 4):
        try:
            run([S5CMD, "--no-sign-request", "--numworkers", str(args.numworkers), "run", str(batch)])
            break
        except RuntimeError:
            print(f"attempt {attempt} failed; retrying...", file=sys.stderr)
    else:
        sys.exit("fetch failed after 3 attempts")
    print(f"done. raw scenarios under {RAW_DIR}")


if __name__ == "__main__":
    main()
